// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatePickerController from "./date_picker_controller.js"
application.register("date-picker", DatePickerController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
